challengeName: "compare-and-contrast"

metadata:
  category: "osint"

spec:
  challengeImage: "us-central1-docker.pkg.dev/k8s-ctf-345001/docker-repo/compare-and-contrast"
  challengeImageVersion: "1.0"
  externalPort: 80
  containerPort: 8000
  replicaCount: 1

ingress:
  enabled: false
  host: "osint1.jstuart.ca"
  pathType: "Prefix"

service:
  enabled: true
  type: LoadBalancer
  annotations:
    external-dns.alpha.kubernetes.io/hostname: osint1.jstuart.ca