challengeName: "biometric-heap"

metadata:
  category: "binary"

spec:
  challengeImage: "us-central1-docker.pkg.dev/k8s-ctf-345001/docker-repo/biometric-heap:1.0"
  externalPort: 3609
  containerPort: 3609
  replicaCount: 1
  privileged: true

ingress:
  enabled: false
  host: "bin1.jstuart.ca"
  pathType: "Prefix"

service:
  enabled: true
  type: LoadBalancer