category: "web"
ingress:
  enabled: true
  challenges:
    web1:
      host: "web1.jstuart.ca"
      pathType: "Prefix"
      challengeName: "blame-the-intern"
      externalPort: 80
      containerPort: 5000
    web2:
      host: "web2.jstuart.ca"
      pathType: "Prefix"
      challengeName: "last-act-of-defiance"
      externalPort: 80
      containerPort: 5000
    web3:
      host: "web3.jstuart.ca"
      pathType: "Prefix"
      challengeName: "old-family-recipe"
      externalPort: 80
      containerPort: 5000
    osint1:
      host: "osint1.jstuart.ca"
      pathType: "Prefix"
      challengeName: "compare-and-contrast"
      externalPort: 80
      containerPort: 8000
