ingress:
  enabled: true
  metadata:
    category: "web"
    annotations:
      kubernetes.io/ingress.class: "gce"
      kubernetes.io/ingress.global-static-ip-name: "ingress-webchalls"
  challenges:
    web1:
      host: "web1.jstuart.ca"
      pathType: "Prefix"
      challengeName: "blame-the-intern"
      externalPort: 80
      containerPort: 5000
    web2:
      host: "web2.jstuart.ca"
      pathType: "Prefix"
      challengeName: "last-act-of-defiance"
      externalPort: 80
      containerPort: 5000
    web3:
      host: "web3.jstuart.ca"
      pathType: "Prefix"
      challengeName: "old-family-recipe"
      externalPort: 80
      containerPort: 5000