challengeName: "old-family-recipe"

metadata:
  category: "web"

spec:
  challengeImage: "us-central1-docker.pkg.dev/k8s-ctf-345001/docker-repo/old-family-recipe:1.0"
  externalPort: 80
  containerPort: 80
  replicaCount: 1

ingress:
  enabled: true
  host: "web3.scriptkitties.dev"
  pathType: "Prefix"

service:
  enabled: true
  type: NodePort