challengeName: "stacks-of-flags"

metadata:
  category: "stacks-of-flags"

spec:
  challengeImage: "us-central1-docker.pkg.dev/k8s-ctf-345001/docker-repo/stacks-of-flags:1.0"
  externalPort: 1946
  containerPort: 1946
  replicaCount: 1
  privileged: true

ingress:
  enabled: false
  host: "bin4.jstuart.ca"
  pathType: "Prefix"

service:
  enabled: true
  type: LoadBalancer