
secretName: database-secrets

volume:
  mysqlClaimName: mysql-volume
  redisClaimName: redis-volume
  ctfdLogsClaimName: ctfd-log-volume
  ctfdUploadClaimName: ctfd-upload-volume
  claimSize: 200Mi
  ctfdLogsSize: 100Mi
  ctfdUploadSize: 500Mi

mysql:
  name: ctfd-mysql-db
  image: mariadb:10.9.2
  port: 3306
  replicas: 1

redis:
  name: ctfd-redis-cache
  image: redis:7.0.4
  port: 6379
  replicas: 1

ctfd:
  name: ctfd
  port: 80
  targetPort: 8000
  gunicornWorkers: 1

ingress:
  enabled: true
  host: "ctfd.jstuart.ca"
  pathType: "Prefix"
  externalPort: 80