apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.challengeName }}
  labels:
    category: {{ .Values.category }}
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.challengeName }}
  ports:
    - port: {{ .Values.externalPort }}
      targetPort: {{ .Values.containerPort }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.challengeName }}
  labels:
    category: {{ .Values.category }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.challengeName }}
  template:
    metadata:
      labels:
        app: {{ .Values.challengeName }}
        category: {{ .Values.category }}
    spec:
      containers:
        - name: {{ .Values.challengeName }}
          image: {{ .Values.challengeImage }}
          ports:
            - containerPort: {{ .Values.containerPort }}

---
