apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-challenges-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.global-static-ip-name: "ingress-webchalls"
spec:
  rules:
  - host: web1.scriptkitties.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: blame-the-intern
            port:
              number: 80
  - host: web2.scriptkitties.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: last-act-of-defiance
            port:
              number: 80
  - host: web3.scriptkitties.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: old-family-recipe
            port:
              number: 80