apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.ctfdLogsClaimName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.ctfdLogsSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.ctfdUploadClaimName }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.ctfdUploadClaimName }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ctfd
  creationTimestamp: null
  name: ctfdPersistentVolumeClaim
    app: ctfd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctfd
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        ctfd: ctfd
        app: ctfd
    spec:
      containers:
      - env:
        - name: ACCESS_LOG
          value: '-'
        - name: DATABASE_URL
          value: mysql+pymysql://ctfd:ctfd@ctfd-mysql-db/ctfd
        - name: ERROR_LOG
          value: '-'
        - name: LOG_FOLDER
          value: /var/log/CTFd
        - name: REDIS_URL
          value: redis://ctfd-redis-cache:6379
        - name: REVERSE_PROXY
          value: "true"
        - name: UPLOAD_FOLDER
          value: /var/uploads
        - name: WORKERS
          value: {{ .Values.ctfd.gunicornWorkers | quote }}
        image: ctfd/ctfd
        name: ctfd
        volumeMounts:
        - mountPath: /var/log/CTFd
          name: {{ .Values.volume.ctfdLogsClaimName }}
        - mountPath: /var/uploads
          name: {{ .Values.volume.ctfdUploadClaimName }}
      restartPolicy: Always
      volumes:
      - name: {{ .Values.volume.ctfdLogsClaimName }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.ctfdLogsClaimName }}
      - name: {{ .Values.volume.ctfdUploadClaimName }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.ctfdUploadClaimName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.ctfd.name }}
spec:
  ports:
  - name: ui
    port: {{ .Values.ctfd.port }}
    protocol: TCP
    targetPort: {{ .Values.ctfd.port }}
  selector:
    app: {{ .Values.ctfd.name }}
  type: ClusterIP