apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.redisClaimName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.claimSize }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name }}
  labels:
    app: {{ .Values.redis.name }}
spec:
  replicas: {{ .Values.redis.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.redis.name }}
  strategy:
    type: Recreate
  template:
    metadata:
        app: {{ .Values.redis.name }}
    spec:
      containers:
      - image: {{ .Values.redis.image }}
        imagePullPolicy: ""
        name: {{ .Values.redis.name }}
        volumeMounts:
        - mountPath: /data
          name: {{ .Values.volume.redisClaimName }}
      restartPolicy: Always
      volumes:
      - name: {{ .Values.volume.redisClaimName }}
        persistentVolumeClaim:
          claimName: {{ .Values.volume.redisClaimName }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.redis.name }}
spec:
  ports:
  - name: redis
    port: {{ .Values.redis.port }}
    protocol: TCP
    targetPort: {{ .Values.redis.port }}
  selector:
    app: {{ .Values.redis.name }}
  type: ClusterIP