apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
type: Opaque
stringData:
  mysql-root-password: VmSSH6h43axq9f^qHH5ovFtBPC!MTb8t#SzLRYds
  mysql-user-password: ^uNdUZ%sDHTMp73Za7sAo3fgLz*JP#Rmy64%L#&M
  