apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.challengeName }}-frontend
  labels:
    category: {{ .Values.metadata.category }}
spec:
  replicas: {{ .Values.spec.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.challengeName }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.challengeName }}-frontend
        category: {{ .Values.metadata.category }}
    spec:
      containers:
        - name: garbage-collector-frontend
          image: "us-central1-docker.pkg.dev/k8s-ctf-345001/docker-repo/garbage-collector-frontend:1.0"
          ports:
            - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.challengeName }}-backend
  labels:
    category: {{ .Values.metadata.category }}
spec:
  replicas: {{ .Values.spec.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.challengeName }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.challengeName }}-backend
        category: {{ .Values.metadata.category }}
    spec:
      containers:
        - name: garbage-collector-backend
          image: "us-central1-docker.pkg.dev/k8s-ctf-345001/docker-repo/garbage-collector-backend:1.0"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: garbage-collector-frontend
  labels:
    category: {{ .Values.metadata.category }}
  annotations:
spec:
  selector:
    app: garbage-collector-frontend
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: garbage-collector-backend
  labels:
    category: {{ .Values.metadata.category }}
  annotations:
spec:
  selector:
    app: garbage-collector-backend
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
---