challengeName: "garbage-collector"

metadata:
  category: "osint"

spec:
  challengeImage: "us-central1-docker.pkg.dev/k8s-ctf-345001/docker-repo/garbage-collector:1.0"
  externalPort: 8081
  containerPort: 80
  replicaCount: 1

ingress:
  enabled: false
  host: "osint3.jstuart.ca"
  pathType: "Prefix"

service:
  enabled: true
  type: NodeBalancer