{{- define "master-chart.ingress" -}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Values.ingress.metadata.category }}-ingress"
  {{- if .Values.ingress.metadata.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.metadata.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
  {{- range $key, $value := .Values.ingress.challenges }}
    - host: {{ $value.host }}
      http:
        paths:
          - pathType: {{ $value.pathType }}
            path: "/"
            backend:
              service:
                name: {{ $value.challengeName }}
                port:
                  number: {{ $value.externalPort }}
  {{- end }}
{{- end }}
{{- end }}