{{- define "master-chart.service" -}}
{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.challengeName  }}
  labels:
    category: {{ .Values.metadata.category }}
spec:
  selector:
    app: {{ .Values.challengeName }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.spec.externalPort }}
      targetPort: {{ .Values.spec.containerPort }}
{{ end }}
{{ end }}