{{- define "master-chart.service" -}}
{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.challengeName  }}
  labels:
    category: {{ .Values.metadata.category }}
  {{- if ((.Values.service).annotations) }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
spec:
  selector:
    app: {{ .Values.challengeName }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.spec.externalPort }}
      targetPort: {{ .Values.spec.containerPort }}
{{ end }}
{{ end }}