challengeName: "mompop-site"

metadata:
  category: "sites"

spec:
  challengeImage: "us-central1-docker.pkg.dev/k8s-ctf-345001/docker-repo/mompop-site"
  challengeImageVersion: "1.0"
  externalPort: 80
  containerPort: 80
  replicaCount: 1

ingress:
  enabled: false
  host: "site1.jstuart.ca"
  pathType: "Prefix"

service:
  enabled: true
  type: ClusterIP
  annotations:
    external-dns.alpha.kubernetes.io/hostname: site1.jstuart.ca