ingress:
  enabled: true
  metadata:
    category: "networks"
    annotations:
      kubernetes.io/ingress.class: "nginx"
      external-dns.alpha.kubernetes.io/hostname: networks1.jstuart.ca
  challenges:
    site1:
      host: "networks1.jstuart.ca"
      pathType: "Prefix"
      challengeName: "scattered-letters"
      externalPort: 80
      containerPort: 80